---

- name: zprofile directory
  file: >
    path=/etc/zprofile.d
    state=directory
  sudo: yes

- name: copy zprofile 
  copy: >
    src=zprofile dest=/etc/zsh/zprofile owner=root group=root mode=0644
  sudo: yes